### ISSUE TITLE
SSH keys for etckeeper not found

### ISSUE THREAD

**Issue by RyanSquared** [hashbang/admin-tools#10]
No compatible private key for etckeeper was found; no packages are installable by any user using two factor authentication until this is fixed or a user adds in a key of their own. Currently I'm setting one up on my own account but I'm unsure of how to set it for the whole organization.

**Comment by RyanSquared** [comment]
We need to add in documentation about the `ssh-add` thing.

**Comment by KellerFuchs** [comment]
Documented a while back
