### ISSUE TITLE
Unuseable keys listed in vault_passphrase.sh

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/admin-tools#107]
- [ ] @RyanSquared, key expired 2017-10-29
- [x] [@drGrove](https://github.com/hashbang/admin-tools/pull/110), key revoked 2017-10-08
- [x] [@KellerFuchs](https://github.com/hashbang/admin-tools/pull/109), subkeys expired 2017-10-22 
- [x] [@DeviaVir](https://github.com/hashbang/admin-tools/pull/108), key revoked 2017-10-25

Same problem as hashbang/password-store#5, same solution.

**Comment by drGrove** [comment]
Fixing with #110
