### ISSUE TITLE
Agree on a baseline Ansible version

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/admin-tools#14]
It would be much easier to improve the playbooks and roles if we know which version of Ansible we are targetting.

Currently, we use some v1.9 features (v1.9 is in `jessie-backports`), but cleaning up on error (in #12 for instance) is much easier using [blocks](https://docs.ansible.com/ansible/playbooks_blocks.html) ... which are a v2.0 feature.
Ansible 2.0 is available in Debian Stretch, and it looks like the pin shouldn't be problematic (unlike the weechat one, which ran into ABI breakages).

Admins in agreement:
- [x] @ChickenNuggers 
- [x] @daurnimator 
- [ ] @drGrove 
- [x] @KellerFuchs 
- [ ] @lrvick

**Comment by KellerFuchs** [comment]
@hashbang/administrators OK for Ansible 2.0?

**Comment by KellerFuchs** [comment]
@hashbang/administrators Ping

**Comment by daurnimator** [comment]
I'm fine with ansible 2.0. Please do wait for a couple of other admins to approve too though.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Ping.

**Comment by RyanSquared** [comment]
No problem with 2. Just stick with a single version.

**Comment by KellerFuchs** [comment]
@ChickenNuggers The thing is (mostly) backwards-compatible, but there are some features which aren't forward-compatible yet useful for cleaner error-handling.

**Comment by KellerFuchs** [comment]
@drGrove @lrvick Ping?

**Comment by daurnimator** [comment]
Didn't you already merge the PR? Seems the debate has ended :P

**Comment by KellerFuchs** [comment]
@drGrove @lrvick didn't comment, but #18 was merged.
