### ISSUE TITLE
Use `dpkg --clear-selections` for the sync playbook

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/admin-tools#3]
This would be much cleaner than parsing with `grep` and `awk`.

_NOTE:_ This is a note to myself, I will work on it  ;)

**Comment by daurnimator** [comment]
> NOTE: This is a note to myself, I will work on it ;)

On github you can assign an issue to yourself over to the right ==>
That let's everyone know that you're handling it :)

**Comment by KellerFuchs** [comment]
Yeah, good point  >_<'

**Comment by RyanSquared** [comment]
Progress / branch? I'd like to see if it's ready at all. @KellerFuchs - feel free to ping me on IRC so I remember to do this.

**Comment by KellerFuchs** [comment]
@ChickenNuggers This was handled in PR #6
