### ISSUE TITLE
Complete the list of admins and SSH keys

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/admin-tools#9]
All the other admins should add themselves and their SSH keys here.

Then, we can make `ansible` remove all the SSH keys that aren't listed here, and the state of the repo will faithfully describe what is on the servers.
- [x] daurnimator
- [x] lrvick
- [x] dgrove
- [x] KellerFuchs
- [x] Alissa

(Expand onto this list when needed)

**Comment by KellerFuchs** [comment]
FYI, adding your key is not enough: you must add yourself to `group_vars/all` too

**Comment by KellerFuchs** [comment]
Also, still waiting on @drGrove and @lrvick

**Comment by KellerFuchs** [comment]
@drGrove @lrvick Ping

**Comment by drGrove** [comment]
pong

**Comment by drGrove** [comment]
https://github.com/drGrove.keys

**Comment by KellerFuchs** [comment]
@lrvick You are the last one left.

**Comment by drGrove** [comment]
By default, we should be able to rely on ${username}.keys for github... Since we use that to pull the repos anyways.

**Comment by KellerFuchs** [comment]
@drGrove Sure, we can rely on them currently.  But @AlissaSquared and myself use different keys there.
In your case (commit https://github.com/hashbang/admin-tools/commit/053360f5d9fbe8557cbf7280179ce1f5f87bc235), the keys are indeed pulled from Github... which makes me realise I didn't think at all how I would ensure that `ansible` fetches those over Tor.
I guess I will just bite the bullet and make myself a Whonix environment for all the #! stuff...

**Comment by drGrove** [comment]
Ah okay

**Comment by drGrove** [comment]
@KellerFuchs just default to @lrvick's github keys until he does something about it.

**Comment by KellerFuchs** [comment]
/me feeds @lrvick and GLaDOS tasty cookies.
